### ISSUE TITLE
It seems that your plugin not work yet

### ISSUE THREAD

**Issue by gusbemacbe** [zpm-zsh/colors#1]
Hello, here are screenshots:

![image](https://user-images.githubusercontent.com/2257024/65936332-bd5b9f80-e3f2-11e9-8b29-8aeee9812c60.png)

![image](https://user-images.githubusercontent.com/2257024/65936390-cc425200-e3f2-11e9-9c4d-8c540bd29b05.png)

**Comment by grigorii-horos** [comment]
@gusbemacbe Use `source` for tests
```bash
source test/test.zsh
```

**Comment by grigorii-horos** [comment]
@gusbemacbe ping

**Comment by gusbemacbe** [comment]
Hello @grigorii-horos 

Sorry for my absence, I have been very busy. As you asked me, I made a test, here's the result:

![image](https://user-images.githubusercontent.com/2257024/89364645-4abdef00-d6a9-11ea-8136-efff4e3c78fa.png)

**Comment by gusbemacbe** [comment]
It seems that I have to source every time when I start the terminal:

![image](https://user-images.githubusercontent.com/2257024/89364758-97092f00-d6a9-11ea-9045-40ebf7422564.png)

**Comment by grigorii-horos** [comment]
> It seems that I have to source every time when I start the terminal

Yes, sure. how would you like to use this plugin?

**Comment by gusbemacbe** [comment]
> Yes, sure. how would you like to use this plugin?

Ah, I found the solution in pure zplug. I missed the two functions `as:plugin` and `defer:1`:

```zsh
zplug "zpm-zsh/colors", use:"colors.plugin.zsh", as:plugin, defer:1
```

It worked now:

![image](https://user-images.githubusercontent.com/2257024/89398404-7364d980-d6e7-11ea-874d-fcef6fa9f282.png)

For it to work, you need `defer:1` to source it before all other plugins. 

I suggest you update your README, regards zplug, because somebody can miss these two functions, so without them, your plugin does not work.
